#!/usr/bin/env python3
"""Idempotent first-run bootstrap inside the TOEFL House ERP product container.

Runs before gunicorn on every start of the ``web`` service. Everything it does
is safe to re-run: completed steps are detected and skipped, migrations always
run (same migrate-replay idempotence proven in the hosted qualification), and
no step ever patches upstream code or weakens a gate.

Steps, in order (mirrors the operator/hosted sequence):

1. Wait for MariaDB and both Redis containers (TCP).
2. Point the bench's Redis URLs at the compose services (set-config --global).
3. Create the site if none exists (new-site, --set-default, mariadb backend).
4. Install missing apps in the proven order: erpnext, education, payments,
   hrms, foundation_security, toefl_house. Already-installed apps are skipped
   (parsed from `bench list-apps`). Synthetic-only flags are never set.
5. Migrate (twice, hosted-parity; the second replay verifies idempotence).
6. Initialize the native site encryption key (the same lazy native mechanism
   the app's own after_install hook uses) so every later backup carries it.
7. Build assets when the sites/assets tree is absent (first boot only; the
   build context bakes no sites tree, the bind-mounted host dir starts empty),
   then merge every app's public/ tree into sites/assets/<app>/ whenever
   anything from a build is missing (first boot, crashed mid-build volume, or
   a recreated container from an updated image). `bench build` leaves the
   built per-app bundles in the app's public/dist/ while the
   sites/assets/assets.json manifest already references them — without this
   sync the static root 404s on the hashed bundles and login silently breaks.
8. On first run only: rotate nothing, but create the Administrator password
   ONCE, write it to ./data/sites/<site>/private/first-run-credentials.txt
   (0600) for the owner, and print a single completion banner.

Secrets: the MariaDB root password arrives via /run/secrets/db.env
(key=value lines, generated by the Windows Install script). Nothing is
invented, re-used, or logged. The Administrator password is generated with
secrets.token_urlsafe and stored only in the credentials file.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
import secrets
import shutil
import socket
import stat
import subprocess
import time

BENCH_DIR = Path(os.environ.get("BENCH_DIR", "/home/frappe/bench"))
SITES_DIR = BENCH_DIR / "sites"
SITE_NAME = os.environ.get("SITE_NAME", "toeflhouse.localhost")
SECRETS_DIR = Path("/run/secrets")
APP_ORDER = ("erpnext", "education", "payments", "hrms", "foundation_security", "toefl_house")
REDIS_URLS = {
    "redis_cache": "redis://redis-cache:6379",
    "redis_queue": "redis://redis-queue:6379",
    "redis_socketio": "redis://redis-queue:6379",
}
SERVICE_ENDPOINTS = (("db", 3306), ("redis-queue", 6379), ("redis-cache", 6379))
SITES_SEED = Path(os.environ.get("SITES_SEED", "/build/sites-seed"))
# Image-derived app registry: always refreshed so an updated image's apps are
# visible. common_site_config.json holds runtime settings: seeded only once.
SEED_REFRESHED = ("apps.txt", "apps.json")
SEED_ONCE = ("common_site_config.json",)


def seed_sites(sites_dir: Path | None = None, seed_dir: Path | None = None) -> list[str]:
    """Restore the bench's sites/ files hidden by the empty host bind mount."""
    sites_dir = sites_dir or SITES_DIR
    seed_dir = seed_dir or SITES_SEED
    sites_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name in SEED_REFRESHED + SEED_ONCE:
        target = sites_dir / name
        if name in SEED_ONCE and target.exists():
            continue
        target.write_bytes((seed_dir / name).read_bytes())
        written.append(name)
    return written


def run_bench(arguments: list[str], *, cwd: Path) -> str:
    # `bench` is the frappe-bench CLI installed in the image's tools venv
    # (/build/tools, on PATH via the Dockerfile), never the site env.
    command = ["bench", *arguments]
    result = subprocess.run(command, cwd=cwd, text=True, capture_output=True, check=False)
    if result.returncode:
        raise RuntimeError(f"bench {' '.join(arguments)} failed (exit {result.returncode}): "
                           f"{(result.stdout + result.stderr)[-1200:]}")
    return (result.stdout or "").strip()


def wait_for_endpoints(endpoints=SERVICE_ENDPOINTS, *, timeout=600) -> None:
    deadline = time.monotonic() + timeout
    pending = list(endpoints)
    while pending and time.monotonic() < deadline:
        host, port = pending[0]
        try:
            with socket.create_connection((host, port), timeout=5):
                pending.pop(0)
                continue
        except OSError:
            time.sleep(2)
    if pending:
        raise RuntimeError(f"services never became reachable: {pending}")


def read_root_password(secrets_dir: Path = SECRETS_DIR) -> str:
    env_file = secrets_dir / "db.env"
    if not env_file.exists():
        raise RuntimeError("missing /run/secrets/db.env (created by the Install script)")
    for line in env_file.read_text().splitlines():
        key, _, value = line.partition("=")
        if key == "MARIADB_ROOT_PASSWORD" and value:
            return value
    raise RuntimeError("db.env lacks MARIADB_ROOT_PASSWORD")


def site_exists(site: str, sites_dir: Path = SITES_DIR) -> bool:
    return (sites_dir / site / "site_config.json").exists()


def parse_installed_apps(bench_list_apps_json_output: str) -> list[str]:
    """`bench --site X list-apps --format json` output → ordered app names."""
    parsed = json.loads(bench_list_apps_json_output or "{}")
    if isinstance(parsed, dict):
        return [str(name) for name in next(iter(parsed.values() or {}), {})] if parsed else []
    if isinstance(parsed, list):
        return [str(name) for name in parsed]
    return []


def missing_apps(installed: list[str], order: tuple = APP_ORDER) -> list[str]:
    """Proven install order minus what the site already has (idempotence)."""
    present = set(installed)
    return [name for name in order if name not in present]


def assets_present(sites_dir: Path = SITES_DIR) -> bool:
    return (sites_dir / "assets" / "js").exists() or (sites_dir / "assets" / "css").exists()


def _app_public(app_root: Path) -> Path | None:
    """The app package's public/ tree: the frappe bench convention is the
    nested package, apps/<name>/<name>/public (every bundled app). Only then
    a top-level apps/<name>/public, or the single inner package carrying a
    public/ dir. None when the app ships no assets.

    Order matters (run 37503724237): the education app's own Vite build
    writes into apps/education/public/frontend/, creating a top-level
    public/ that shadows the real nested one — syncing that instead of the
    package's left the hashed dist bundles out of the static root again."""
    for candidate in (app_root / app_root.name / "public", app_root / "public"):
        if candidate.is_dir():
            return candidate
    inner = [p for p in app_root.iterdir() if p.is_dir() and (p / "public").is_dir()]
    return inner[0] / "public" if len(inner) == 1 else None


def sync_built_assets(sites_dir: Path = SITES_DIR, apps_dir: Path | None = None) -> list[str]:
    """Merge each app's public/ tree into sites/assets/<app>/ where missing.

    The static root is served verbatim (SharedDataMiddleware, no manifest
    resolution at serve time), while page rendering resolves bundle names
    through sites/assets/assets.json — so every file a manifest can point at
    must physically exist under sites/assets/<app>/. `bench build` does not
    reliably place its own per-app output there (observed 2026-10-06:
    education's public/dist/js/education.bundle.<hash>.js present in the app,
    absent from sites/assets/education, login page 404ing it). The merge is
    additive plus same-name overwrite: it never deletes, it is idempotent,
    and its cost on a complete volume is a stat walk (skips the copy).
    """
    apps_dir = apps_dir or (BENCH_DIR / "apps")
    assets = sites_dir / "assets"
    if not apps_dir.is_dir():
        return []
    synced = []
    for app_root in sorted(p for p in apps_dir.iterdir() if p.is_dir()):
        public = _app_public(app_root)
        if public is None:
            continue
        dest = assets / app_root.name
        missing = [
            file
            for file in public.rglob("*")
            if file.is_file() and not (dest / file.relative_to(public)).is_file()
        ]
        if not missing:
            continue
        shutil.copytree(public, dest, dirs_exist_ok=True)
        synced.append(app_root.name)
    return synced


def public_assets_missing(sites_dir: Path = SITES_DIR, apps_dir: Path | None = None) -> list[str]:
    """Re-walk after the sync: every app public/ file must exist under
    sites/assets/<app>/, because that is the verbatim static root. Returns
    the missing paths (empty = the served page cannot 404 on a built asset)."""
    apps_dir = apps_dir or (BENCH_DIR / "apps")
    missing = []
    if not apps_dir.is_dir():
        return missing
    for app_root in sorted(p for p in apps_dir.iterdir() if p.is_dir()):
        public = _app_public(app_root)
        if public is None:
            continue
        dest = sites_dir / "assets" / app_root.name
        for file in public.rglob("*"):
            if file.is_file() and not (dest / file.relative_to(public)).is_file():
                missing.append(f"{app_root.name}/{file.relative_to(public).as_posix()}")
    return missing


def write_credentials(site: str, admin_password: str, sites_dir: Path = SITES_DIR) -> Path:
    credentials = sites_dir / site / "private" / "first-run-credentials.txt"
    credentials.parent.mkdir(parents=True, exist_ok=True)
    if credentials.exists():
        return credentials
    credentials.write_text(
        "TOEFL House ERP — first-run Administrator credentials\n"
        "======================================================\n"
        f"Site: {site}\nUsername: Administrator\nPassword: {admin_password}\n\n"
        "Keep this file private. You can change the password after logging in\n"
        "(User Menu → My Profile → Set New Password). If you lose it before any\n"
        "backup, use the Repair script: it cannot and will not print secrets.\n",
        encoding="utf-8",
    )
    credentials.chmod(stat.S_IRUSR | stat.S_IWUSR)
    return credentials


def bootstrap(site: str = SITE_NAME, *, log=print) -> dict:
    started = time.monotonic()
    actions: list[str] = []
    wait_for_endpoints(SERVICE_ENDPOINTS)
    actions.append("services-reachable")
    seed_sites()
    actions.append("sites-seeded")
    for key, value in REDIS_URLS.items():
        run_bench(["set-config", "--global", key, value], cwd=BENCH_DIR)
    actions.append("redis-configured")
    root_password = read_root_password(SECRETS_DIR)

    first_run = not site_exists(site, SITES_DIR)
    if first_run:
        admin_password = secrets.token_urlsafe(24)
        run_bench(["new-site", site, "--db-type", "mariadb", "--db-host", "db", "--db-port", "3306",
                   "--db-root-password", root_password, "--db-password", secrets.token_urlsafe(24),
                   "--admin-password", admin_password, "--mariadb-user-host-login-scope", "%",
                   "--set-default"], cwd=BENCH_DIR)
        actions.append("site-created")
    else:
        admin_password = None
        actions.append("site-present")

    installed = parse_installed_apps(run_bench(["--site", site, "list-apps", "--format", "json"], cwd=BENCH_DIR))
    needed = missing_apps(installed)
    for name in needed:
        run_bench(["--site", site, "install-app", name], cwd=BENCH_DIR)
        actions.append(f"installed-{name}")
    if not needed:
        actions.append("apps-present")

    run_bench(["--site", site, "migrate"], cwd=BENCH_DIR)
    actions.append("migrated")
    # Command parity with the hosted migrate-replay: a second migrate proves the
    # migration chain is stable and idempotent, never skipped even on cold DBs.
    run_bench(["--site", site, "migrate"], cwd=BENCH_DIR)
    actions.append("migrate-replayed")

    # Native lazy encryption-key initialization (same call after_install uses):
    run_bench(["--site", site, "execute", "frappe.utils.password.get_encryption_key"], cwd=BENCH_DIR)
    actions.append("encryption-key-initialized")

    if not assets_present(SITES_DIR):
        run_bench(["build"], cwd=BENCH_DIR)
        actions.append("assets-built")
    else:
        actions.append("assets-present")

    # `bench build` leaves the built per-app bundles in the app's public/ tree
    # while sites/assets/assets.json already references them; make the static
    # root physically complete, then prove it: every manifest entry must
    # resolve to an existing file, or this boot fails fast with the names.
    synced = sync_built_assets(SITES_DIR)
    if synced:
        actions.append(f"assets-synced:{len(synced)}")
    missing_assets = public_assets_missing(SITES_DIR)
    if missing_assets:
        raise RuntimeError(
            "served-asset 404s would occur (built app assets missing from the "
            f"static root): {missing_assets[:8]}{' ...' if len(missing_assets) > 8 else ''}"
        )
    actions.append("assets-complete")

    if admin_password:
        credentials = write_credentials(site, admin_password, SITES_DIR)
        run_bench(["--site", site, "enable-scheduler"], cwd=BENCH_DIR)
        actions.append("scheduler-enabled")
        log(f"[toefl-house-erp] first run complete. Owner credentials: {credentials}")
    return {"site": site, "actions": actions, "seconds": round(time.monotonic() - started, 3)}


def main() -> int:
    summary = bootstrap()
    print(json.dumps(summary))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
