#!/usr/bin/env python3
"""Idempotent one-shot initialization in the TOEFL House ERP product stack.

Compose runs this short-lived ``bootstrap`` service successfully before the
long-lived ``web`` service starts. Everything is safe to re-run: completed
steps are detected and skipped, migrations always run (including the proven
migrate replay), and no step patches upstream code or weakens a gate.

Steps, in order (mirrors the operator/hosted sequence):

1. Wait for MariaDB and both Redis containers (TCP).
2. Point the bench's Redis URLs at the compose services (set-config --global).
3. Create the site if none exists through pinned Frappe's native installer
   (`_new_site`, MariaDB backend, default site).
4. On first run, create the Administrator password ONCE and atomically stage
   it at mode 0600 on the persistent sites volume before invoking Frappe's
   native installer. Publish it to
   ./data/sites/<site>/private/first-run-credentials.txt immediately after
   site creation; a retry reuses the pending value if either step is interrupted.
5. Install missing apps in the proven order: erpnext, education, payments,
   hrms, foundation_security, toefl_house. Already-installed apps are skipped
   (parsed from `bench list-apps`). Synthetic-only flags are never set.
6. Migrate (twice, hosted-parity; the second replay verifies idempotence).
7. Initialize the native site encryption key (the same lazy native mechanism
   the app's own after_install hook uses) so every later backup carries it.
8. Build assets when the sites/assets tree is absent (first boot only; the
   build context bakes no sites tree, the bind-mounted host dir starts empty),
   then merge every app's public/ tree into sites/assets/<app>/ whenever
   anything from a build is missing (first boot, crashed mid-build volume, or
   a recreated container from an updated image). `bench build` leaves the
   built per-app bundles in the app's public/dist/ while the
   sites/assets/assets.json manifest already references them — without this
   sync the static root 404s on the hashed bundles and login silently breaks.
9. Enable the scheduler idempotently on every boot. This repairs a partial
   first boot that stopped before scheduler activation; it does not rotate
   Administrator credentials or repeat one-time secret writes.

Secrets: the MariaDB root password arrives only in the short-lived
bootstrap service via /run/bootstrap-secrets/db.env (key=value lines,
generated by the Windows Install script). The web service never mounts that
file. Site-creation secrets are sent to the pinned Bench Python process over
stdin, not command-line arguments or logs. The Administrator password is
generated with secrets.token_urlsafe, atomically staged mode 0600 on the
persistent sites volume, then published into the site's private credentials file.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
import re
import secrets
import stat
import shutil
import socket
import subprocess
import sys
import time

BENCH_DIR = Path(os.environ.get("BENCH_DIR", "/home/frappe/bench"))
SITES_DIR = BENCH_DIR / "sites"
SITE_NAME = os.environ.get("SITE_NAME", "toeflhouse.localhost")
ENV_PYTHON = BENCH_DIR / "env" / "bin" / "python"
SECRETS_DIR = Path("/run/bootstrap-secrets")
APP_ORDER = ("erpnext", "education", "payments", "hrms", "foundation_security", "toefl_house")
REDIS_URLS = {
    "redis_cache": "redis://redis-cache:6379",
    "redis_queue": "redis://redis-queue:6379",
    "redis_socketio": "redis://redis-queue:6379",
}
SERVICE_ENDPOINTS = (("db", 3306), ("redis-queue", 6379), ("redis-cache", 6379))
SITES_SEED = Path(os.environ.get("SITES_SEED", "/build/sites-seed"))
# Image-derived app registry: always refreshed so an updated image's apps are
# visible. common_site_config.json holds runtime settings: seeded only once.
SEED_REFRESHED = ("apps.txt", "apps.json")
SEED_ONCE = ("common_site_config.json",)


def seed_sites(sites_dir: Path | None = None, seed_dir: Path | None = None) -> list[str]:
    """Restore the bench's sites/ files hidden by the empty host bind mount."""
    sites_dir = sites_dir or SITES_DIR
    seed_dir = seed_dir or SITES_SEED
    sites_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name in SEED_REFRESHED + SEED_ONCE:
        target = sites_dir / name
        if name in SEED_ONCE and target.exists():
            continue
        target.write_bytes((seed_dir / name).read_bytes())
        written.append(name)
    return written


def run_bench(arguments: list[str], *, cwd: Path) -> str:
    # `bench` is the frappe-bench CLI installed in the image's tools venv
    # (/build/tools, on PATH via the Dockerfile), never the site env.
    command = ["bench", *arguments]
    result = subprocess.run(command, cwd=cwd, text=True, capture_output=True, check=False)
    if result.returncode:
        # Do not surface argv or child output: other Bench operations can add
        # credential-bearing values later, and failures may echo config data.
        raise RuntimeError(f"bench operation failed (exit {result.returncode})")
    return (result.stdout or "").strip()


def wait_for_endpoints(endpoints=SERVICE_ENDPOINTS, *, timeout=600) -> None:
    deadline = time.monotonic() + timeout
    pending = list(endpoints)
    while pending and time.monotonic() < deadline:
        host, port = pending[0]
        try:
            with socket.create_connection((host, port), timeout=5):
                pending.pop(0)
                continue
        except OSError:
            time.sleep(2)
    if pending:
        raise RuntimeError(f"services never became reachable: {pending}")


def read_root_password(secrets_dir: Path = SECRETS_DIR) -> str:
    env_file = secrets_dir / "db.env"
    if not env_file.exists():
        raise RuntimeError("missing /run/bootstrap-secrets/db.env (created by the Install script)")
    for line in env_file.read_text().splitlines():
        key, _, value = line.partition("=")
        if key == "MARIADB_ROOT_PASSWORD" and value:
            return value
    raise RuntimeError("db.env lacks MARIADB_ROOT_PASSWORD")


_NATIVE_SITE_FAILURE_MARKER = "TOEFL_NATIVE_SITE_EXCEPTION="
_NATIVE_SITE_ERRNO_MARKER = "TOEFL_NATIVE_SITE_ERRNO="
_NATIVE_SITE_FRAMES_MARKER = "TOEFL_NATIVE_SITE_FRAMES="
_NATIVE_EXCEPTION_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]{0,127}\Z")

_CREATE_SITE_SCRIPT = r'''
import json, os, re, sys, traceback
frappe = None
initialized = False
failure = None
try:
    import frappe
    from frappe.installer import _new_site, update_site_config
    payload = json.load(sys.stdin)
    site = payload["site"]
    # Bench's native new-site command runs from sites/: Frappe resolves its
    # relative log paths there, while setup_module_map reads apps.txt from the
    # same directory. Pass it explicitly so the native API is cwd-independent.
    frappe.init(site, sites_path=os.getcwd(), new_site=True)
    initialized = True
    _new_site(
        payload.get("db_name"), site,
        db_root_username="root",
        db_root_password=payload["db_root_password"],
        admin_password=payload["admin_password"],
        db_password=payload["db_password"],
        db_type=payload.get("db_type", "mariadb"),
        db_host=payload.get("db_host", "db"),
        db_port=int(payload.get("db_port", 3306)),
        setup_db=True,
        mariadb_user_host_login_scope=payload.get("mariadb_user_host_login_scope", "%"),
    )
    if payload.get("set_default_site", True):
        update_site_config(
            "default_site", site, validate=False,
            site_config_path=payload.get(
                "common_site_config_path",
                "/home/frappe/bench/sites/common_site_config.json"),
        )
except Exception as error:
    failure = error

if initialized:
    try:
        frappe.destroy()
    except Exception as error:
        if failure is None:
            failure = error

if failure is not None:
    # Surface only the program-defined exception type, numeric OS code, and
    # bounded frame names/line numbers. Its message, paths, source text, and
    # full traceback may contain sensitive upstream diagnostics; keep them
    # captured by the parent.
    name = type(failure).__name__
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]{0,127}", name):
        print("TOEFL_NATIVE_SITE_EXCEPTION=" + name, file=sys.stderr, flush=True)
    if isinstance(failure, OSError):
        code = getattr(failure, "errno", None)
        if type(code) is int and 0 <= code <= 65535:
            print("TOEFL_NATIVE_SITE_ERRNO=" + str(code), file=sys.stderr, flush=True)
    frames = []
    for frame in traceback.extract_tb(failure.__traceback__)[-6:]:
        if re.fullmatch(r"[A-Za-z0-9_<>.-]{1,128}", frame.name):
            frames.append(frame.name + "|" + str(frame.lineno))
    if frames:
        print("TOEFL_NATIVE_SITE_FRAMES=" + ",".join(frames),
              file=sys.stderr, flush=True)
    raise failure
'''


class NativeSiteCreationError(RuntimeError):
    """A safe site-creation failure containing no child output or credentials."""

    def __init__(self, returncode: int | None, failure_type: str | None = None,
                 failure_errno: int | None = None,
                 failure_frames: tuple[str, ...] | None = None):
        self.returncode = returncode
        self.failure_type = (failure_type if isinstance(failure_type, str)
                             and _NATIVE_EXCEPTION_NAME.fullmatch(failure_type)
                             else None)
        self.failure_errno = (failure_errno if type(failure_errno) is int
                              and 0 <= failure_errno <= 65535 else None)
        frames = failure_frames if isinstance(failure_frames, (tuple, list)) else ()
        valid_frames = (len(frames) <= 6 and all(
            isinstance(frame, str) and re.fullmatch(
                r"[A-Za-z0-9_<>.-]{1,128}:[1-9][0-9]{0,5}", frame)
            for frame in frames))
        self.failure_frames = tuple(frames) if valid_frames else ()
        message = "secure native site creation failed"
        if returncode is not None:
            message += f" (exit {returncode})"
        if self.failure_type:
            message += f"; exception type: {self.failure_type}"
        if self.failure_errno is not None:
            message += f"; OS error code: {self.failure_errno}"
        if self.failure_frames:
            message += "; frames: " + ",".join(self.failure_frames)
        message += "; sensitive diagnostics were withheld"
        super().__init__(message)


def _native_site_failure_type(stderr: str) -> str | None:
    """Extract the one safe exception-class marker, never an error message."""
    markers = [line[len(_NATIVE_SITE_FAILURE_MARKER):]
               for line in (stderr or "").splitlines()
               if line.startswith(_NATIVE_SITE_FAILURE_MARKER)]
    if len(markers) != 1 or not _NATIVE_EXCEPTION_NAME.fullmatch(markers[0]):
        return None
    return markers[0]


def _native_site_failure_errno(stderr: str) -> int | None:
    """Extract one bounded numeric OS error code; never parse error text."""
    markers = [line[len(_NATIVE_SITE_ERRNO_MARKER):]
               for line in (stderr or "").splitlines()
               if line.startswith(_NATIVE_SITE_ERRNO_MARKER)]
    if len(markers) != 1 or not re.fullmatch(r"(?:0|[1-9][0-9]{0,4})", markers[0]):
        return None
    code = int(markers[0])
    return code if code <= 65535 else None


def _native_site_failure_frames(stderr: str) -> tuple[str, ...]:
    """Extract one compact frame-name/line marker; omit paths and source text."""
    markers = [line[len(_NATIVE_SITE_FRAMES_MARKER):]
               for line in (stderr or "").splitlines()
               if line.startswith(_NATIVE_SITE_FRAMES_MARKER)]
    if len(markers) != 1:
        return ()
    raw_frames = markers[0].split(",")
    if not 1 <= len(raw_frames) <= 6:
        return ()
    frames = []
    for raw in raw_frames:
        name, separator, line_number = raw.partition("|")
        if (not separator
                or not re.fullmatch(r"[A-Za-z0-9_<>.-]{1,128}", name)
                or not re.fullmatch(r"[1-9][0-9]{0,5}", line_number)):
            return ()
        frames.append(f"{name}:{line_number}")
    return tuple(frames)


def create_site(site: str, root_password: str, admin_password: str,
                db_password: str, *, db_host: str = "db", db_port: int = 3306,
                db_type: str = "mariadb", mariadb_user_host_login_scope: str = "%",
                set_default_site: bool = True, db_name: str | None = None) -> None:
    """Create a site without placing credentials in argv, output, or logs."""
    if (not isinstance(site, str)
            or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9.-]{0,252}", site)
            or db_type != "mariadb"
            or not isinstance(db_host, str) or not db_host
            or isinstance(db_port, bool) or not isinstance(db_port, int)
            or not 1 <= db_port <= 65535
            or not isinstance(set_default_site, bool)
            or (db_name is not None and (not isinstance(db_name, str)
                or not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]{0,63}", db_name)))):
        raise RuntimeError("native Frappe site-creation input is invalid")
    payload = json.dumps({
        "site": site,
        "db_root_password": root_password,
        "admin_password": admin_password,
        "db_password": db_password,
        "db_type": db_type,
        "db_name": db_name,
        "db_host": db_host,
        "db_port": db_port,
        "mariadb_user_host_login_scope": mariadb_user_host_login_scope,
        "set_default_site": set_default_site,
        "common_site_config_path": str(BENCH_DIR / "sites" / "common_site_config.json"),
    })
    try:
        result = subprocess.run(
            [str(ENV_PYTHON), "-c", _CREATE_SITE_SCRIPT],
            cwd=BENCH_DIR / "sites",
            input=payload,
            text=True,
            errors="replace",
            capture_output=True,
            check=False,
        )
    except OSError as error:
        # Keep executable/path/message diagnostics out of logs; only the
        # exception class and a validated numeric OS error code are safe.
        raise NativeSiteCreationError(
            None, type(error).__name__, getattr(error, "errno", None)) from None
    if result.returncode:
        # The child receives credentials on stdin. Never forward its exception,
        # argv, paths, source text or captured output: only a validated type,
        # numeric OS code, and compact function-name/line summary are safe.
        failure_type = _native_site_failure_type(result.stderr)
        raise NativeSiteCreationError(
            result.returncode,
            failure_type,
            _native_site_failure_errno(result.stderr),
            _native_site_failure_frames(result.stderr) if failure_type else (),
        ) from None


def site_exists(site: str, sites_dir: Path = SITES_DIR) -> bool:
    return (sites_dir / site / "site_config.json").exists()


def parse_installed_apps(bench_list_apps_json_output: str) -> list[str]:
    """`bench --site X list-apps --format json` output → ordered app names."""
    parsed = json.loads(bench_list_apps_json_output or "{}")
    if isinstance(parsed, dict):
        return [str(name) for name in next(iter(parsed.values() or {}), {})] if parsed else []
    if isinstance(parsed, list):
        return [str(name) for name in parsed]
    return []


def missing_apps(installed: list[str], order: tuple = APP_ORDER) -> list[str]:
    """Proven install order minus what the site already has (idempotence)."""
    present = set(installed)
    return [name for name in order if name not in present]


def assets_present(sites_dir: Path = SITES_DIR) -> bool:
    assets = sites_dir / "assets"
    return ((assets / "assets.json").is_file()
            and (assets / "js").is_dir()
            and (assets / "css").is_dir())


def manifest_assets_missing(sites_dir: Path = SITES_DIR) -> list[str]:
    """Verify every local manifest URL resolves inside the served assets root."""
    assets = sites_dir / "assets"
    manifest = assets / "assets.json"
    try:
        mappings = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        return ["assets.json"]
    if not isinstance(mappings, dict):
        return ["assets.json"]

    missing = []
    for url in mappings.values():
        if not isinstance(url, str) or not url.startswith("/assets/"):
            continue
        relative = url[len("/assets/"):]
        parts = relative.split("/")
        if not relative or any(part in {"", ".", ".."} for part in parts):
            missing.append(relative or "assets.json")
            continue
        if not assets.joinpath(*parts).is_file():
            missing.append(relative)
    return sorted(set(missing))


def _app_public(app_root: Path) -> Path | None:
    """The app package's public/ tree: the frappe bench convention is the
    nested package, apps/<name>/<name>/public (every bundled app). Only then
    a top-level apps/<name>/public, or the single inner package carrying a
    public/ dir. None when the app ships no assets.

    Order matters (run 37503724237): the education app's own Vite build
    writes into apps/education/public/frontend/, creating a top-level
    public/ that shadows the real nested one — syncing that instead of the
    package's left the hashed dist bundles out of the static root again."""
    for candidate in (app_root / app_root.name / "public", app_root / "public"):
        if candidate.is_dir():
            return candidate
    inner = [p for p in app_root.iterdir() if p.is_dir() and (p / "public").is_dir()]
    return inner[0] / "public" if len(inner) == 1 else None


def sync_built_assets(sites_dir: Path = SITES_DIR, apps_dir: Path | None = None) -> list[str]:
    """Merge each app's public/ tree into sites/assets/<app>/ where missing.

    The static root is served verbatim (SharedDataMiddleware, no manifest
    resolution at serve time), while page rendering resolves bundle names
    through sites/assets/assets.json — so every file a manifest can point at
    must physically exist under sites/assets/<app>/. `bench build` does not
    reliably place its own per-app output there (observed 2026-10-06:
    education's public/dist/js/education.bundle.<hash>.js present in the app,
    absent from sites/assets/education, login page 404ing it). The merge is
    additive plus same-name overwrite: it never deletes, it is idempotent,
    and its cost on a complete volume is a stat walk (skips the copy).
    """
    apps_dir = apps_dir or (BENCH_DIR / "apps")
    assets = sites_dir / "assets"
    if not apps_dir.is_dir():
        return []
    synced = []
    for app_root in sorted(p for p in apps_dir.iterdir() if p.is_dir()):
        public = _app_public(app_root)
        if public is None:
            continue
        dest = assets / app_root.name
        missing = [
            file
            for file in public.rglob("*")
            if file.is_file() and not (dest / file.relative_to(public)).is_file()
        ]
        if not missing:
            continue
        shutil.copytree(public, dest, dirs_exist_ok=True)
        synced.append(app_root.name)
    return synced


def public_assets_missing(sites_dir: Path = SITES_DIR, apps_dir: Path | None = None) -> list[str]:
    """Re-walk after the sync: every app public/ file must exist under
    sites/assets/<app>/, because that is the verbatim static root. Returns
    the missing paths (empty = the served page cannot 404 on a built asset)."""
    apps_dir = apps_dir or (BENCH_DIR / "apps")
    missing = []
    if not apps_dir.is_dir():
        return missing
    for app_root in sorted(p for p in apps_dir.iterdir() if p.is_dir()):
        public = _app_public(app_root)
        if public is None:
            continue
        dest = sites_dir / "assets" / app_root.name
        for file in public.rglob("*"):
            relative = file.relative_to(public)
            if file.is_file() and not (dest / relative).is_file():
                # Report stable POSIX asset URLs/paths on every host, including
                # the Windows packaging-test runner.
                missing.append(f"{app_root.name}/{relative.as_posix()}")
    return missing


def _credentials_content(site: str, admin_password: str) -> str:
    return (
        "TOEFL House ERP — first-run Administrator credentials\n"
        "======================================================\n"
        f"Site: {site}\nUsername: Administrator\nPassword: {admin_password}\n\n"
        "Keep this file private. You can change the password after logging in\n"
        "(User Menu → My Profile → Set New Password). If you lose it before any\n"
        "backup, use the Repair script: it cannot and will not print secrets.\n")


def _create_private_credentials_file(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        raise RuntimeError("first-run credentials already exist; refusing to overwrite") from None
    try:
        if hasattr(os, "fchmod"):
            os.fchmod(descriptor, 0o600)
        else:  # pragma: no cover - bootstrap runs in Linux containers
            os.chmod(path, 0o600)
        stream = os.fdopen(descriptor, "w", encoding="utf-8", newline="\n")
        descriptor = -1
        with stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
    except Exception:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            path.unlink()
        except OSError:
            pass
        raise RuntimeError("first-run credentials could not be stored safely") from None
    return path


def _validate_private_credentials(path: Path) -> None:
    try:
        safe = not path.is_symlink() and path.is_file()
        if os.name != "nt":
            # The product bootstrap runs inside its Linux container, where
            # mode 0600 is the enforced file-permission contract. Windows
            # host test filesystems do not report POSIX mode bits faithfully;
            # the Windows job still exercises atomic/write-once behavior,
            # while the Linux runtime test below retains the real mode check.
            safe = safe and stat.S_IMODE(path.stat().st_mode) == 0o600
    except OSError:
        safe = False
    if not safe:
        raise RuntimeError("first-run credentials path is unsafe")


def _pending_credentials_path(site: str, sites_dir: Path = SITES_DIR) -> Path:
    if (not isinstance(site, str)
            or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9.-]{0,252}", site)
            or sites_dir.is_symlink()):
        raise RuntimeError("first-run credentials location is unsafe")
    return sites_dir / f".{site}.first-run-credentials.pending"


def _read_pending_admin_password(path: Path, site: str) -> str:
    _validate_private_credentials(path)
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError):
        raise RuntimeError("pending first-run credentials are invalid") from None
    expected_site = f"Site: {site}"
    password_lines = [line[len("Password: "):] for line in lines
                      if line.startswith("Password: ")]
    if (expected_site not in lines or "Username: Administrator" not in lines
            or len(password_lines) != 1 or not password_lines[0]):
        raise RuntimeError("pending first-run credentials are invalid")
    return password_lines[0]


def _publish_pending_credentials(pending: Path, site: str,
                                 sites_dir: Path = SITES_DIR) -> Path:
    credentials = sites_dir / site / "private" / "first-run-credentials.txt"
    _validate_private_credentials(pending)
    site_root = sites_dir / site
    private_root = site_root / "private"
    if any(path.is_symlink() for path in (sites_dir, site_root, private_root)):
        raise RuntimeError("first-run credentials location is unsafe")
    credentials.parent.mkdir(parents=True, exist_ok=True)
    if any(path.is_symlink() for path in (sites_dir, site_root, private_root)):
        raise RuntimeError("first-run credentials location is unsafe")
    if credentials.exists() or credentials.is_symlink():
        try:
            identical = (not credentials.is_symlink() and credentials.is_file()
                         and os.path.samefile(pending, credentials))
        except OSError:
            identical = False
        if not identical:
            raise RuntimeError(
                "first-run credentials already exist; refusing to replace them")
        pending.unlink()
        return credentials
    try:
        # The site and pending file share the persistent sites volume. Linking
        # publishes atomically and refuses to replace any pre-existing file.
        os.link(pending, credentials, follow_symlinks=False)
    except Exception:
        raise RuntimeError(
            "first-run credentials could not be published safely; pending credentials were preserved") from None
    try:
        pending.unlink()
    except OSError:
        # Both paths refer to the same private file; the next boot will detect
        # that identity and finish removing only the temporary staging name.
        pass
    return credentials


def write_credentials(site: str, admin_password: str, sites_dir: Path = SITES_DIR) -> Path:
    """Write the one-time password atomically with private mode from creation."""
    _pending_credentials_path(site, sites_dir)  # validates the site/path components
    if not isinstance(admin_password, str) or not admin_password:
        raise RuntimeError("first-run Administrator password is invalid")
    credentials = sites_dir / site / "private" / "first-run-credentials.txt"
    if credentials.exists() or credentials.is_symlink():
        _validate_private_credentials(credentials)
        return credentials
    return _create_private_credentials_file(
        credentials, _credentials_content(site, admin_password))


def bootstrap(site: str = SITE_NAME, *, log=print) -> dict:
    started = time.monotonic()
    actions: list[str] = []
    wait_for_endpoints(SERVICE_ENDPOINTS)
    actions.append("services-reachable")
    seed_sites()
    actions.append("sites-seeded")
    for key, value in REDIS_URLS.items():
        run_bench(["set-config", "--global", key, value], cwd=BENCH_DIR)
    actions.append("redis-configured")

    pending_credentials = _pending_credentials_path(site, SITES_DIR)
    if (SITES_DIR / site).is_symlink():
        raise RuntimeError("configured site path is unsafe")
    first_run = not site_exists(site, SITES_DIR)
    credentials = None
    credentials_path = SITES_DIR / site / "private" / "first-run-credentials.txt"
    if first_run:
        if credentials_path.exists() or credentials_path.is_symlink():
            raise RuntimeError(
                "first-run credentials exist without a site; refusing to create a new Administrator password")
        if pending_credentials.exists() or pending_credentials.is_symlink():
            # Reuse the exact password if an earlier attempt created the site
            # but exited before the pending credential could be published.
            admin_password = _read_pending_admin_password(pending_credentials, site)
        else:
            admin_password = secrets.token_urlsafe(24)
            _create_private_credentials_file(
                pending_credentials, _credentials_content(site, admin_password))
        root_password = read_root_password(SECRETS_DIR)
        create_site(site, root_password, admin_password, secrets.token_urlsafe(24))
        credentials = _publish_pending_credentials(
            pending_credentials, site, SITES_DIR)
        actions.extend(("site-created", "credentials-written"))
    else:
        admin_password = None
        actions.append("site-present")
        if pending_credentials.exists() or pending_credentials.is_symlink():
            # Recover the one-time password before later app/migration steps;
            # a failed _new_site wrapper must not strand an unknown login.
            credentials = _publish_pending_credentials(
                pending_credentials, site, SITES_DIR)
            actions.append("credentials-recovered")

    installed = parse_installed_apps(run_bench(["--site", site, "list-apps", "--format", "json"], cwd=BENCH_DIR))
    needed = missing_apps(installed)
    for name in needed:
        run_bench(["--site", site, "install-app", name], cwd=BENCH_DIR)
        actions.append(f"installed-{name}")
    if not needed:
        actions.append("apps-present")

    run_bench(["--site", site, "migrate"], cwd=BENCH_DIR)
    actions.append("migrated")
    # Command parity with the hosted migrate-replay: a second migrate proves the
    # migration chain is stable and idempotent, never skipped even on cold DBs.
    run_bench(["--site", site, "migrate"], cwd=BENCH_DIR)
    actions.append("migrate-replayed")

    # Native lazy encryption-key initialization (same call after_install uses):
    run_bench(["--site", site, "execute", "frappe.utils.password.get_encryption_key"], cwd=BENCH_DIR)
    actions.append("encryption-key-initialized")

    if not assets_present(SITES_DIR):
        run_bench(["build"], cwd=BENCH_DIR)
        actions.append("assets-built")
    else:
        actions.append("assets-present")

    # `bench build` leaves the built per-app bundles in the app's public/ tree
    # while sites/assets/assets.json already references them; make the static
    # root physically complete, then prove it: every manifest entry must
    # resolve to an existing file, or this boot fails fast with the names.
    synced = sync_built_assets(SITES_DIR)
    if synced:
        actions.append(f"assets-synced:{len(synced)}")
    missing_assets = public_assets_missing(SITES_DIR)
    if missing_assets:
        raise RuntimeError(
            "served-asset 404s would occur (built app assets missing from the "
            f"static root): {missing_assets[:8]}{' ...' if len(missing_assets) > 8 else ''}"
        )
    actions.append("assets-complete")
    missing_manifest_assets = manifest_assets_missing(SITES_DIR)
    if missing_manifest_assets:
        raise RuntimeError(
            "served-asset 404s would occur (manifest URLs missing from the "
            f"static root): {missing_manifest_assets[:8]}"
        )
    actions.append("assets-manifest-complete")

    # This is idempotent and also repairs a first boot that stopped after site
    # creation but before scheduler setup. The password file was already stored
    # privately immediately after native site creation.
    run_bench(["--site", site, "enable-scheduler"], cwd=BENCH_DIR)
    actions.append("scheduler-enabled")
    if credentials:
        log(f"[toefl-house-erp] first run complete. Owner credentials: {credentials}")
    return {"site": site, "actions": actions, "seconds": round(time.monotonic() - started, 3)}


def main() -> int:
    try:
        summary = bootstrap()
    except NativeSiteCreationError as error:
        # Deliberately emit only a validated exception class, numeric OS error
        # code, and compact frame-name/line summary; messages, paths, source
        # text and full tracebacks remain private to the captured process.
        print(str(error), file=sys.stderr)
        return 1
    print(json.dumps(summary))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
