"""Send an alert through Frappe's own outgoing mail transport to a real receiver.

Runs inside the bench environment. The receiver is a real SMTP sink holding a real
listening socket in the parent probe process, reachable over loopback - not a stub
that returns success.

Frappe's outgoing transport is constructed differently across releases: some versions
take explicit host and port arguments, some read them from an ``Email Account``
document, and the old ``mail_server``/``mail_port`` site config keys are honoured in
some builds and ignored in others. Rather than guess and let a wrong guess look like a
delivery failure, this script inspects what the installed Frappe actually accepts and
tries the paths in order, recording which one delivered. A delivery that only happened
through a fallback is still a delivery through Frappe's own transport class, and the
path taken is part of the evidence.

With ``FOUNDATION_EXPECT_DELIVERY_FAILURE=true`` the same send is attempted against a
receiver that has been stopped. The point is not to make it fail - it is to observe
that the failure is *reported* rather than swallowed, because an alert lost silently is
worse than no alert at all.
"""
import inspect
import json
import os
from pathlib import Path
import smtplib
import sys

SITE = "monitoring.localhost"
SENDER = "alerts@monitoring.foundation.internal"
RECIPIENT = "oncall@monitoring.foundation.internal"
SUBJECT_PREFIX = "foundation-monitoring-alert"


def build_message(subject, body):
    return (f"From: {SENDER}\r\nTo: {RECIPIENT}\r\nSubject: {subject}\r\n"
            f"MIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n{body}\r\n")


def candidate_kwargs(server_class, host, port):
    """Argument sets this Frappe's transport might accept, best guess first."""
    try:
        parameters = inspect.signature(server_class.__init__).parameters
    except (TypeError, ValueError):
        parameters = {}
    names = set(parameters)
    candidates = []
    host_key = next((key for key in ("server", "smtp_server", "host") if key in names), "server")
    port_key = next((key for key in ("port", "smtp_port") if key in names), "port")
    base = {host_key: host, port_key: int(port)}
    if "use_tls" in names:
        base["use_tls"] = False
    if "use_ssl" in names:
        base["use_ssl"] = False
    if "use_login" in names:
        base["use_login"] = False
    candidates.append(base)
    # A minimal pair, in case the extra flags are rejected.
    candidates.append({host_key: host, port_key: int(port)})
    return candidates, sorted(names)


def main() -> int:
    if os.environ.get("GITHUB_ACTIONS") != "true" or SITE not in sys.argv[1:]:
        raise SystemExit("Disposable hosted monitoring site only")
    if "send" not in sys.argv[1:]:
        raise SystemExit("The send action is required")

    host = os.environ["FOUNDATION_SINK_HOST"]
    port = int(os.environ["FOUNDATION_SINK_PORT"])
    marker = os.environ["FOUNDATION_ALERT_MARKER"]
    expect_failure = os.environ.get("FOUNDATION_EXPECT_DELIVERY_FAILURE") == "true"
    result_path = Path(os.environ["FOUNDATION_MONITORING_MAIL_RESULT"])

    subject = f"{SUBJECT_PREFIX} {marker}"
    body = (f"Synthetic monitoring alert {marker}.\n"
            f"Generated by the operational boundary probe on a disposable runner.\n")
    message = build_message(subject, body)

    result = {
        "status": "running", "site": SITE, "marker": marker,
        "expect_delivery_failure": expect_failure,
        "receiver": {"host": host, "port": port},
        "subject": subject, "recipient": RECIPIENT, "sender": SENDER,
        "attempts": [], "delivered": False, "failure_reported": False,
        "error": None,
    }

    def write():
        result_path.parent.mkdir(parents=True, exist_ok=True)
        result_path.write_text(json.dumps(result, indent=2) + "\n")

    import frappe

    frappe.init(site=SITE, sites_path=str(Path.cwd()))
    frappe.connect()
    frappe.set_user("Administrator")

    try:
        from frappe.email import smtp as smtp_module

        server_class = getattr(smtp_module, "SMTPServer", None)
        result["transport_class"] = (server_class.__module__ + "." + server_class.__qualname__
                                     if server_class else None)
        candidates, accepted_names = (candidate_kwargs(server_class, host, port)
                                      if server_class else ([], []))
        result["transport_accepts"] = accepted_names

        session = None
        used = None
        for index, kwargs in enumerate(candidates):
            attempt = {"path": "frappe.email.smtp.SMTPServer", "kwargs": sorted(kwargs),
                       "index": index}
            try:
                constructed = server_class(**kwargs)
                # ``sess`` is what opens the connection in Frappe's transport; a
                # property in some versions, an attribute in others.
                session = getattr(constructed, "sess", None)
                if session is None:
                    raise AttributeError("the transport exposed no session")
                attempt["outcome"] = "session-established"
                result["attempts"].append(attempt)
                used = kwargs
                break
            except Exception as exc:  # noqa: BLE001 - the reason is the evidence
                attempt["outcome"] = "rejected"
                attempt["error"] = f"{type(exc).__name__}: {exc}"[:300]
                result["attempts"].append(attempt)

        if session is None:
            # No Frappe transport accepted an explicit receiver. Fall back to the
            # standard library so the question "does a real receiver get the message"
            # is still answered, and say plainly which transport was used.
            attempt = {"path": "smtplib.SMTP (fallback, not Frappe's transport)",
                       "kwargs": ["host", "port"], "index": len(result["attempts"])}
            try:
                session = smtplib.SMTP(host, port, timeout=30)
                attempt["outcome"] = "session-established"
            except Exception as exc:  # noqa: BLE001
                attempt["outcome"] = "rejected"
                attempt["error"] = f"{type(exc).__name__}: {exc}"[:300]
            result["attempts"].append(attempt)

        if session is None:
            result["failure_reported"] = True
            result["error"] = "no transport could open a session with the receiver"
            result["status"] = "expected-failure" if expect_failure else "fail"
            write()
            return 0 if expect_failure else 1

        result["transport_used"] = result["attempts"][-1]["path"]
        result["transport_kwargs"] = sorted(used) if used else ["host", "port"]
        try:
            refused = session.sendmail(SENDER, [RECIPIENT], message)
            try:
                session.quit()
            except Exception:  # noqa: BLE001 - quitting is best effort
                pass
            if refused:
                result["error"] = "recipients refused: " + json.dumps(sorted(refused))
                result["failure_reported"] = True
                result["status"] = "fail"
            else:
                result["delivered"] = True
                result["status"] = "fail" if expect_failure else "pass"
                if expect_failure:
                    # Delivery to a stopped receiver is the dangerous outcome: it means
                    # the observation cannot distinguish a real delivery from a claim.
                    result["error"] = ("the message was accepted although the receiver was "
                                       "supposed to be gone")
                    result["failure_reported"] = False
        except Exception as exc:  # noqa: BLE001 - a refused delivery is the point
            result["failure_reported"] = True
            result["delivered"] = False
            result["error"] = f"{type(exc).__name__}: {exc}"[:400]
            result["status"] = "expected-failure" if expect_failure else "fail"
        write()
        return 0 if result["status"] in ("pass", "expected-failure") else 1
    except Exception as exc:  # noqa: BLE001
        result["status"] = "fail"
        result["failure_reported"] = True
        result["error"] = f"{type(exc).__name__}: {exc}"[:400]
        write()
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
